### ISSUE TITLE
Add function sim800

### ISSUE THREAD

**Issue by KawinJoe** [erdemarslan/GSMSim#10]
I want you to add a function to display the number of the incoming call.

"IncomingCall(char *number)"

**Comment by erdemarslan** [comment]
I will release new version of library. It will be add, generally we send AT command to module and module answer us, then we look answer and make some process. Incoming calls or messages come suddenly and we must catch them when they came. We will fix that with different way. Wait next version.

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
