### ISSUE TITLE
Signal Strength 

### ISSUE THREAD

**Issue by KawinJoe** [erdemarslan/GSMSim#11]
Show 99 only. Sim800c connect to operator.  I think cmd not work.

**Comment by RemiLelaidier** [comment]
Same thing for me with a SIM900.
I only get 99, but i'm able to send SMS or Phone Call.

**Comment by erdemarslan** [comment]
I check it. I have only Sim800L and it works good. If i found another models of simcom i will test it again.

**Comment by erdemarslan** [comment]
I will release new version of GSMSim in a few days. You will check it again.

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
