### ISSUE TITLE
Repeat calling

### ISSUE THREAD

**Issue by Dremarcus** [erdemarslan/GSMSim#12]
If I use more numbers to call, only first number is active. 
Serial.println("Calling the number " + String(phone_no));
  Serial.println(gsm.call(phone_no));
  delay(10000);
  Serial.println("Call hang off");
  gsm.callHangoff();
  delay(10000);
  
Serial.println("Calling the number " + String(phone_no));
  Serial.println(gsm.call(phone_no));
  delay(10000);
  Serial.println("Call hang off");
  gsm.callHangoff();

No posible to second call

**Comment by erdemarslan** [comment]
It will be fixed at new version. I will release new version in a few days. Thanks.

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
