### ISSUE TITLE
Adding a command that help us to reject an incoming call. 

### ISSUE THREAD

**Issue by QuangKhuongIoT** [erdemarslan/GSMSim#17]
In some project, when we only want to send a sms or make a call, and we no need to answer any incoming call, which make module sim busy in a long period of time. So i think we should have a command that help us to reject an imcoming call positively.
Thank you for all your helps.

**Comment by erdemarslan** [comment]
It will be on in new version which is release in a few days. Thanks.

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
