### ISSUE TITLE
About HttpPost 

### ISSUE THREAD

**Issue by rtarta** [erdemarslan/GSMSim#18]
Hi Erdem,
Is there any method like HttpPost. In library i see only httpGet methot wish to have httpPost.
Teşekkürler.

**Comment by JavierBlacksmith** [comment]
I was just wandering this exact thing, I need to post to a firebase db

**Comment by erdemarslan** [comment]
I am working on this. Probably on new version i will add this.

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
