### ISSUE TITLE
Adding callback or disable on the fly SMS receiving

### ISSUE THREAD

**Issue by gamelaster** [erdemarslan/GSMSim#2]
AT+CNMI=0,0
This disables SMS on the fly receiving, since, if this is not disabled, the responses not must be parsed correctly

**Comment by erdemarslan** [comment]
i check this. Thanks for your attention.

**Comment by luckydonald** [comment]
What's the result of this?

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
