### ISSUE TITLE
problem reading sms

### ISSUE THREAD

**Issue by Speppe** [erdemarslan/GSMSim#21]
I tried to use your library with the following code to read sms

  Serial.println("Unread sms");
  String list = "NO_SMS";
  while (list == "NO_SMS") {
    list = gsm.smsListUnread();
    Serial.println("No sms");
    delay(2000);
  }
  uint8_t index = list.substring(11).toInt();
  Serial.print("Reading sms n. ");
  Serial.println(index);
  String sms = gsm.smsRead(index, true);
  Serial.println(sms);

It receive sms but, when it read, the answer is always INDEX_NO_ERROR

thanks for your help

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
