### ISSUE TITLE
GSMSim and Arduino Nano + SIM800C

### ISSUE THREAD

**Issue by robpan3** [erdemarslan/GSMSim#25]
Hallo Erdem, 
I have tested with success your library "GSMSim" with Arduino UNO in every examples, but I cannot send Email ONLY with the Arduino Nano with the same hardware configuration.
I put a LIPO battery directly to VBAT and GND of my SIM800C (with Arduino UNO and NANO) and my Arduino Nano is powered by the USB cable (to have the debug).
I receive these messages:

  GSMSim Library - Send Email Example
  Connect to Internet: 1
  Set gmail smtp configuration: 1
  Write email to someone: ERROR:TITLE_NOT_SET
  Send email... : SUCCESS:EMAIL_SEND
  Close Internet: 1

But I receive the Email with the "title", but without the "body".
Thanks a lot if you have any suggestion.
Roberto
Graz - Austria

**Comment by erdemarslan** [comment]
I will release new version in a few days. Can you check it again when i release new version? Thanks.
