### ISSUE TITLE
Code enhancements label: enhancement

### ISSUE THREAD

**Issue by nabeelkirmani** [erdemarslan/GSMSim#26]
- Comparison is always false due to limited range of data type in [bool GSMSim::fmSetVolume(uint8_t volume)](https://github.com/erdemarslan/GSMSim/blob/master/GSMSim.cpp#L1168)

- Unused parameter 'imeino' in [bool GSMSim::moduleIMEIChange(char* imeino)](https://github.com/erdemarslan/GSMSim/blob/master/GSMSim.cpp#L350)

- Unused parameter 'read' in [String GSMSim::gprsHTTPGet(String url, bool read)](https://github.com/erdemarslan/GSMSim/blob/master/GSMSim.cpp#L1510)

- No return, in function returning non-void in [bool GSM::callHangoff()](https://github.com/erdemarslan/GSMSim/blob/master/GSMSim.cpp#L497) and similar functions.

**Comment by erdemarslan** [comment]
I will release new version in a few days. Thanks.
