### ISSUE TITLE
questions: How To use string as sms message?

### ISSUE THREAD

**Issue by Trpplayer79** [erdemarslan/GSMSim#37]
How can you use a string variable as sms message?

For example:

```
#define SMSNUMBER "+3xxxxxxxxxx"
String MESSAGE = "";   // depending on the reason is this filled with different text by the program/sketch/code

void loop() {
sms.send(SMSNUMBER, MESSAGE);
}
```
Tthis gives the fault message:

```
In function 'void SMSSend()': [Sketch]:[Line:Char]: error: no matching function for call to 
'GSMSimSMS::send(const char [13], String&)' sms.send(SMSNUMBER, MESSAGE);
```

When i remove the variable as message does the code compile correctly:
```
sms.send(SMSNUMBER, "Test Message");
```

This code also doesn't work:
```sms.send(SMSNUMBER, "\""MESSAGE"\"");```
fault message:
```
In function 'void SMSSend()': error: unable to find string literal operator 'operator""MESSAGE' with 'const char [3]', 'unsigned int' arguments
     sms.send(SMSNUMBER, "\""MESSAGE"\"");```

**Comment by erdemarslan** [comment]
Please try to convert string to char array. Like this.
```
String MESSAGE="This is message";
int strLen = MESSAGE.lenght() + 1;
char messageChar[strLen];
MESSAGE.toCharArray(messageChar, strLen);
sms.send(SMSNUMBER, messageChar);
```

Reference: [Arduino toCharArray](https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/tochararray/)

**Comment by erdemarslan** [comment]
If your issue solved, please close topic. Thanks.

**Comment by Trpplayer79** [comment]
Thank you, This solved the issue!

Suggestion: integrate this somehow into the example sketch.
