### ISSUE TITLE
How to set a APN

### ISSUE THREAD

**Issue by jwinfield2022** [erdemarslan/GSMSim#38]
I am trying to set the APN but I get an error.

`Serial.println(http.gprsInit("www.vodafone.net.nz","","")); `

But I get the error

`GSMSim_HTTP:91:58: error: invalid use of void expression
 Serial.println(http.gprsInit("www.vodafone.net.nz","",""));
`

With a chevron pointing to the bracket before the ;.
                                                                                       
Seems like the syntax is correct?

**Comment by Tracesol** [comment]
Could be because http.gprsInit returns a void and you can't print a void. Just run it whitout Serial.println().
