### ISSUE TITLE
Can't gsm.gprsHTTPGet to deal with long URLs

### ISSUE THREAD

**Issue by gusantor** [erdemarslan/GSMSim#4]
Hello, thanks for your library

Using gsm.gprsHTTPGet , I'm able to get results from URLs like www.google.com or www.mysite.com

But not from www.mysite.com/one/or/two/branches

It's just me ?

Thanks in advance

**Comment by gusantor** [comment]
Hello

I've just tried, same results ... sort of intermittent, never get a 200 response code, except when I use just a domain (www.google.com, www.mysite.com)

Never the less, I always get an IP

Response I wait for is just json 180 chars

..and I needed to add #include <Wire.h>, if not, arduino UNO keeps rebooting

Thanks

**Comment by erdemarslan** [comment]
Can you send your codes and connection diagram to me? I want to test it.

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
