### ISSUE TITLE
Arduino Mega 2560 not Support

### ISSUE THREAD

**Issue by Oky12** [erdemarslan/GSMSim#5]
hai.... i have project to make a controller relay with sms. and i tested this library on my arduino mega. its work with pin 9 and 10. but the pin comunication is useless if i using digital pin. i try change pin from 9 and 10 to pin 14 and 15 (TX3 and RX3), but not working. why is not working?. does the communication pin must to use serial?

**Comment by erdemarslan** [comment]
This library only work with softwareserial. Maybe future update i will add hardware serial too.

**Comment by KawinJoe** [comment]
I used Arduino mega 2560, It's work.

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
