### ISSUE TITLE
Module is not connected to gsm operator

### ISSUE THREAD

**Issue by jakecorn** [erdemarslan/GSMSim#6]
Hi, Please help me with my problem. 
I'm using s800l module with arduino uno. I tried to send and sms using  the library but i don't received any text from my module to my phone. I tried to run GSMSim_Module_Info and i got the following details:

GSMSim Library - Module Information

Manufacturer:		SIMCOM Ltd
Model:			SIMCOM SIM800L
Revision:		1418B04SIM800L24

O
IMEI:			
IMSI:			864764036478012
ICCID:			515020210958145
Is Connected?:		0
Signal Quality:		99
Operator:		T+CSQ

+CSQ: 27,0

OK

Operator From Sim:	GLOBE

Is there something wrong with the output? It says not connected? What does exactly it mean?
I'm from Philippines.

Thank you for making this library.

**Comment by erdemarslan** [comment]
It says module not connect to operator. Maybe your location not better for connection or signal strange not better for connection. Sometimes some sim cards not connect to operator with this modules. Specialy sim800l module which has red pcb is not connect with some simcards. In my country there are 3 operators have, but sim800l with red pcb is connect with only one operators simcard. But i have sim800l 5v blue pcb, its connect to operator with all operators simcard. Its not librarys fault. Please try with change your simcard and change your location. You can use better antenna for this module.
