### ISSUE TITLE
smsREAD not working

### ISSUE THREAD

**Issue by zsarwar** [erdemarslan/GSMSim#8]
Hi,

I have been trying to use the SMSread function. 
It always returns back index no error, however manual executing the +CMGR is working fine.
Is there any update

**Comment by erdemarslan** [comment]
Can you send your codes and any screenshot for this.

**Comment by zsarwar** [comment]
void loop() {
// put your main code here, to run repeatedly:

if((gsm.smsListUnread())=="NO_SMS")
{
 Serial.println("Awaiting new SMS");
 Serial.println("");
 delay(1000);
}
else
{
 Serial.println("New SMS Recevied");
 Serial.println("");
 delay(1000);

 Serial.print("Reading SMS : ");
 Serial.println(gsm.smsRead(1));
 Serial.println("");
 delay(1000);  
 
 for(;;) {} // This test code will put endless loop and stop furtehr execution

}

![image](https://user-images.githubusercontent.com/44923568/48677438-7ffd7300-eb8e-11e8-8729-0b6c30060853.png)

**Comment by erdemarslan** [comment]
Your error about message index no error. There is no message on index no = 1 in your sim card or module.

Change your codes like this in your loop.

`
void loop() {
  String indexno = gsm.smsListUnread();

  if indexno == "NO_SMS" {
    Serial.println("Awaiting new SMS");
    Serial.println("");
    delay(1000);
  } else {
    Serial.println("New SMS Recevied");
    Serial.println("");
    delay(1000);
    // now indexno like this => 21 or 23,24 etc
    // check is it contains comma (,)
    if indexno.indexOf(",") == -1 {
      // only one number
      Serial.print("Reading SMS : ");
      Serial.println(gsm.smsRead(atoi(indexno)));
      Serial.println("");
      delay(1000);
    } else {
      // split each number whichs are seperated with comma
      // then read each message in loop
      // You can look this example for this
      // https://arduino.stackexchange.com/questions/1013/how-do-i-split-an-incoming-string/1033#1033
    }
  }
}
`

**Comment by zsarwar** [comment]
Still getting error while compiling.

![image](https://user-images.githubusercontent.com/44923568/48678017-db336380-eb96-11e8-8183-42499208da3b.png)

**Comment by erdemarslan** [comment]
Change marked line to

`Serial.println(gsm.smsRead(indexno.toInt()));`

**Comment by zsarwar** [comment]
Getting the same Index no error message again 

![image](https://user-images.githubusercontent.com/44923568/48678115-7842cc00-eb98-11e8-8e75-068f0c3aaaca.png)

**Comment by erdemarslan** [comment]
Can you print indexno variable? 
Please add
`Serial.println(indexno);`
and add your screenshot here.

**Comment by zsarwar** [comment]
Sent

**Comment by zsarwar** [comment]
Can you please confirm if you have received my code

**Comment by erdemarslan** [comment]
Yes your code received to me. I test it and there is no error. This issue about incoming message indicator. You must change incoming message indicator. You must change your message indicator to save option. I missed it when i coding this library. I update codes and add smsChangeIncomingIndicator function. You can change your indicator to show or save. smsChangeIncomingIndicator(true) save message for read. smsChangeIncomingIndicator(false) show the messages while program runnig.

I advise dont list messages, read them when they come. So i added readSerial command for this.

**Comment by zsarwar** [comment]
Dear ,
smsRead() is still not working. 
I have simplified my code as below and the output as followed.

![image](https://user-images.githubusercontent.com/44923568/49178231-a7132c00-f368-11e8-9942-f74dd77a00ae.png)

![image](https://user-images.githubusercontent.com/44923568/49178321-e6417d00-f368-11e8-9b62-ee2478d06d95.png)

**Comment by erdemarslan** [comment]
GSMSim is updated. Please check the examples. You can update library from Arduino Library Manager or manually.
